

Sandwiches.destroy_all
Breads.destroy_all
Condiments.destroy_all
Vegetables.destroy_all
Salads.destroy_all
Salad_Dressings.destroy_all
Flatizzas.destroy_all
Beverages.destroy_all
Desserts.destroy_all
Other.destroy_all

Sandwiches = Sandwiches.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "6 inch Black Forest Ham",
		serving_size: 56,
		calories: 75,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 520,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 10,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch Oven Roasted Chicken",
		serving_size: 70,
		calories: 105,
		calories_from_fat: 20,
		total_fat: 3,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 330,
		carbohydrates: 4,
		dietary_fiber: 1,
		sugars: 2,
		protein: 15,
		vitamin_a: 2,
		vitamin_c: 12,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch Roast Beef",
		serving_size: 70,
		calories: 105,
		calories_from_fat: 20,
		total_fat: 3,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 380,
		carbohydrates: 2,
		dietary_fiber: 1,
		sugars: 1,
		protein: 16,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 10
	},
	{
		name: "6 inch Subway Club®",
		serving_size: 77,
		calories: 95,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 520,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 1,
		protein: 15,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Sweet Onion Chicken Teriyaki",
		serving_size: 106,
		calories: 155,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 50,
		sodium: 490,
		carbohydrates: 14,
		dietary_fiber: 1,
		sugars: 10,
		protein: 17,
		vitamin_a: 4,
		vitamin_c: 7,
		calcium: 5,
		iron: 5
	},
	{
		name: "6 inch Turkey Breast",
		serving_size: 56,
		calories: 65,
		calories_from_fat: 10,
		total_fat: 1.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 390,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 1,
		protein: 10,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch Turkey Breast & Ham",
		serving_size: 56,
		calories: 65,
		calories_from_fat: 15,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 450,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 10,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch Veggie Delite®",
		serving_size: 0,
		calories: 15,
		calories_from_fat: 0,
		total_fat: 0.5,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 1,
		dietary_fiber: 1,
		sugars: 0,
		protein: 0,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	# {
	# 	name: "Black Forest Ham Mini Sub",
	# 	serving_size: -25,
	# 	calories: -35,
	# 	calories_from_fat: 0,
	# 	total_fat: 0.5,
	# 	saturated_fat: 0,
	# 	trans_fat: 0,
	# 	cholesterol: 10,
	# 	sodium: 170,
	# 	carbohydrates: -13,
	# 	dietary_fiber: -1,
	# 	sugars: -1,
	# 	protein: 2,
	# 	vitamin_a: 0,
	# 	vitamin_c: -3,
	# 	calcium: -10,
	# 	iron: -5
	# },
	# {
	# 	name: "Roast Beef Mini Sub",
	# 	serving_size: -16,
	# 	calories: -15,
	# 	calories_from_fat: 5,
	# 	total_fat: 1,
	# 	saturated_fat: 0.5,
	# 	trans_fat: 0,
	# 	cholesterol: 25,
	# 	sodium: 110,
	# 	carbohydrates: -13,
	# 	dietary_fiber: 0,
	# 	sugars: -1,
	# 	protein: 6,
	# 	vitamin_a: 0,
	# 	vitamin_c: -3,
	# 	calcium: -10,
	# 	iron: 0
	# },
	# {
	# 	name: "Turkey Breast Mini Sub",
	# 	serving_size: -25,
	# 	calories: -35,
	# 	calories_from_fat: 0,
	# 	total_fat: 0,
	# 	saturated_fat: 0,
	# 	trans_fat: 0,
	# 	cholesterol: 10,
	# 	sodium: 100,
	# 	carbohydrates: -13,
	# 	dietary_fiber: -1,
	# 	sugars: -1,
	# 	protein: 2,
	# 	vitamin_a: 0,
	# 	vitamin_c: -3,
	# 	calcium: -10,
	# 	iron: -5
	# },
	# {
	# 	name: "Veggie Delite® Mini Sub",
	# 	serving_size: -54,
	# 	calories: -65,
	# 	calories_from_fat: -5,
	# 	total_fat: -0.5,
	# 	saturated_fat: -0.5,
	# 	trans_fat: 0,
	# 	cholesterol: 0,
	# 	sodium: -90,
	# 	carbohydrates: -14,
	# 	dietary_fiber: -1,
	# 	sugars: -2,
	# 	protein: -2,
	# 	vitamin_a: 0,
	# 	vitamin_c: -3,
	# 	calcium: -10,
	# 	iron: -5
	# },
	{
		name: "6 inch B.L.T.",
		serving_size: -9,
		calories: 105,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 370,
		carbohydrates: 0,
		dietary_fiber: 1,
		sugars: 0,
		protein: 7,
		vitamin_a: 2,
		vitamin_c: -10,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch BBQ Oven Roasted Chicken Melt",
		serving_size: 105,
		calories: 195,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 590,
		carbohydrates: 15,
		dietary_fiber: 2,
		sugars: 11,
		protein: 19,
		vitamin_a: 4,
		vitamin_c: 17,
		calcium: 10,
		iron: 0
	},
	{
		name: "6 inch BBQ Steak & Bacon Melt",
		serving_size: 111,
		calories: 245,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 5.5,
		trans_fat: 0,
		cholesterol: 55,
		sodium: 1110,
		carbohydrates: 15,
		dietary_fiber: 1,
		sugars: 11,
		protein: 21,
		vitamin_a: 4,
		vitamin_c: 7,
		calcium: 10,
		iron: 10
	},
	{
		name: "6 inch Big Hot Pastrami",
		serving_size: 124,
		calories: 365,
		calories_from_fat: 290,
		total_fat: 29,
		saturated_fat: 10.5,
		trans_fat: 0,
		cholesterol: 85,
		sodium: 1190,
		carbohydrates: 4,
		dietary_fiber: 1,
		sugars: 1,
		protein: 21,
		vitamin_a: 4,
		vitamin_c: 27,
		calcium: 10,
		iron: 10
	},
	{
		name: "6 inch Big Philly Cheesesteak",
		serving_size: 134,
		calories: 285,
		calories_from_fat: 130,
		total_fat: 15,
		saturated_fat: 8.5,
		trans_fat: 1,
		cholesterol: 85,
		sodium: 1000,
		carbohydrates: 8,
		dietary_fiber: 2,
		sugars: 2,
		protein: 30,
		vitamin_a: 9,
		vitamin_c: 2,
		calcium: 20,
		iron: 10
	},
	{
		name: "6 inch Chicken & Bacon Ranch Melt (includes cheese)",
		serving_size: 128,
		calories: 355,
		calories_from_fat: 230,
		total_fat: 26,
		saturated_fat: 9.5,
		trans_fat: 0.5,
		cholesterol: 95,
		sodium: 770,
		carbohydrates: 4,
		dietary_fiber: 1,
		sugars: 2,
		protein: 27,
		vitamin_a: 9,
		vitamin_c: 7,
		calcium: 20,
		iron: 5
	},
	{
		name: "6 inch Chicken Cordon Bleu Melt",
		serving_size: 131,
		calories: 195,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 75,
		sodium: 790,
		carbohydrates: 10,
		dietary_fiber: 1,
		sugars: 7,
		protein: 24,
		vitamin_a: 4,
		vitamin_c: 7,
		calcium: 10,
		iron: 5
	},
	{
		name: "6 inch Cold Cut Combo",
		serving_size: 64,
		calories: 145,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 45,
		sodium: 750,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 1,
		protein: 9,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 5,
		iron: 5
	},
	{
		name: "6 inch Fritos® Chicken Enchilada Melt",
		serving_size: 135,
		calories: 365,
		calories_from_fat: 220,
		total_fat: 24,
		saturated_fat: 6.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 890,
		carbohydrates: 17,
		dietary_fiber: 3,
		sugars: 3,
		protein: 17,
		vitamin_a: 24,
		vitamin_c: 12,
		calcium: 15,
		iron: 10
	},
	{
		name: "6 inch Italian B.M.T.®",
		serving_size: 63,
		calories: 195,
		calories_from_fat: 130,
		total_fat: 14,
		saturated_fat: 5.5,
		trans_fat: 0,
		cholesterol: 45,
		sodium: 980,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 12,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	{
		name: "6 inch Meatball Marinara",
		serving_size: 139,
		calories: 265,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 6.5,
		trans_fat: 0.5,
		cholesterol: 30,
		sodium: 640,
		carbohydrates: 16,
		dietary_fiber: 4,
		sugars: 6,
		protein: 13,
		vitamin_a: 19,
		vitamin_c: 17,
		calcium: 5,
		iron: 10
	},
	{
		name: "6 inch Spicy Italian",
		serving_size: 59,
		calories: 265,
		calories_from_fat: 200,
		total_fat: 22,
		saturated_fat: 8.5,
		trans_fat: 0.5,
		cholesterol: 50,
		sodium: 1210,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 12,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Spicy Tuna",
		serving_size: 95,
		calories: 305,
		calories_from_fat: 230,
		total_fat: 26,
		saturated_fat: 4,
		trans_fat: 0.5,
		cholesterol: 40,
		sodium: 570,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 13,
		vitamin_a: 19,
		vitamin_c: 7,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Sriracha Chicken Melt",
		serving_size: 95,
		calories: 185,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 70,
		sodium: 590,
		carbohydrates: 3,
		dietary_fiber: 1,
		sugars: 2,
		protein: 19,
		vitamin_a: 9,
		vitamin_c: 12,
		calcium: 10,
		iron: 5
	},
	{
		name: "6 inch Sriracha Steak Melt",
		serving_size: 95,
		calories: 215,
		calories_from_fat: 100,
		total_fat: 12,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 930,
		carbohydrates: 6,
		dietary_fiber: 2,
		sugars: 3,
		protein: 18,
		vitamin_a: 9,
		vitamin_c: 7,
		calcium: 10,
		iron: 10
	},
	{
		name: "6 inch Steak & Bacon Melt",
		serving_size: 133,
		calories: 285,
		calories_from_fat: 120,
		total_fat: 14,
		saturated_fat: 6.5,
		trans_fat: 0.5,
		cholesterol: 85,
		sodium: 1270,
		carbohydrates: 8,
		dietary_fiber: 2,
		sugars: 3,
		protein: 30,
		vitamin_a: 4,
		vitamin_c: 2,
		calcium: 10,
		iron: 15
	},
	{
		name: "6 inch Steak and Cheese",
		serving_size: 81,
		calories: 165,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 4,
		trans_fat: 0,
		cholesterol: 50,
		sodium: 750,
		carbohydrates: 5,
		dietary_fiber: 1,
		sugars: 2,
		protein: 18,
		vitamin_a: 4,
		vitamin_c: 2,
		calcium: 10,
		iron: 5
	},
	{
		name: "6 inch Subway Club® with Avocado",
		serving_size: 112,
		calories: 155,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 520,
		carbohydrates: 6,
		dietary_fiber: 4,
		sugars: 2,
		protein: 16,
		vitamin_a: 4,
		vitamin_c: 182,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Subway Melt® (includes cheese)",
		serving_size: 76,
		calories: 155,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 45,
		sodium: 850,
		carbohydrates: 4,
		dietary_fiber: 1,
		sugars: 2,
		protein: 15,
		vitamin_a: 4,
		vitamin_c: 2,
		calcium: 10,
		iron: 0
	},
	{
		name: "6 inch Tuna",
		serving_size: 74,
		calories: 265,
		calories_from_fat: 190,
		total_fat: 23,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 35,
		sodium: 320,
		carbohydrates: 1,
		dietary_fiber: 1,
		sugars: 0,
		protein: 12,
		vitamin_a: 2,
		vitamin_c: 2,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Turkey & Bacon Avocado",
		serving_size: 100,
		calories: 175,
		calories_from_fat: 90,
		total_fat: 11,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 30,
		sodium: 580,
		carbohydrates: 6,
		dietary_fiber: 4,
		sugars: 1,
		protein: 14,
		vitamin_a: 4,
		vitamin_c: 182,
		calcium: 0,
		iron: 5
	},
	{
		name: "6 inch Turkey Jalapeno Melt",
		serving_size: 99,
		calories: 215,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 820,
		carbohydrates: 5,
		dietary_fiber: 1,
		sugars: 1,
		protein: 13,
		vitamin_a: 9,
		vitamin_c: 7,
		calcium: 10,
		iron: 5
	},
	{
		name: "6 inch Tuscan Chicken Melt",
		serving_size: 105,
		calories: 165,
		calories_from_fat: 50,
		total_fat: 6,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 770,
		carbohydrates: 9,
		dietary_fiber: 1,
		sugars: 5,
		protein: 19,
		vitamin_a: 9,
		vitamin_c: 17,
		calcium: 10,
		iron: 5
	}
]);

Breads = Breads.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "6 inch Flatbread",
		serving_size: 87,
		calories: 220,
		calories_from_fat: 40,
		total_fat: 4.5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 340,
		carbohydrates: 38,
		dietary_fiber: 2,
		sugars: 2,
		protein: 7,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 10,
		iron: 15
	},
	{
		name: "6 inch 9-Grain Wheat Bread",
		serving_size: 78,
		calories: 210,
		calories_from_fat: 20,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 280,
		carbohydrates: 40,
		dietary_fiber: 4,
		sugars: 5,
		protein: 8,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 30,
		iron: 15
	},
	{
		name: "6 inch Hearty Italian Bread",
		serving_size: 75,
		calories: 210,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 280,
		carbohydrates: 41,
		dietary_fiber: 2,
		sugars: 5,
		protein: 7,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 30,
		iron: 15
	},
	{
		name: "6 inch Honey Oat",
		serving_size: 82,
		calories: 230,
		calories_from_fat: 20,
		total_fat: 3,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 280,
		carbohydrates: 43,
		dietary_fiber: 4,
		sugars: 6,
		protein: 8,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 30,
		iron: 15
	},
	{
		name: "6 inch Italian (White) Bread",
		serving_size: 71,
		calories: 200,
		calories_from_fat: 20,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 280,
		carbohydrates: 38,
		dietary_fiber: 1,
		sugars: 5,
		protein: 7,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 30,
		iron: 15
	},
	{
		name: "6 inch Italian Herbs & Cheese",
		serving_size: 82,
		calories: 250,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 470,
		carbohydrates: 40,
		dietary_fiber: 2,
		sugars: 5,
		protein: 9,
		vitamin_a: 2,
		vitamin_c: 0,
		calcium: 40,
		iron: 15
	},
	{
		name: "6 inch Monterey Cheddar",
		serving_size: 82,
		calories: 240,
		calories_from_fat: 50,
		total_fat: 6,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 340,
		carbohydrates: 38,
		dietary_fiber: 2,
		sugars: 5,
		protein: 10,
		vitamin_a: 2,
		vitamin_c: 0,
		calcium: 40,
		iron: 15
	},
	{
		name: "6 inch Parmesan Oregano Bread",
		serving_size: 75,
		calories: 220,
		calories_from_fat: 25,
		total_fat: 2.5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 420,
		carbohydrates: 40,
		dietary_fiber: 2,
		sugars: 5,
		protein: 8,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 35,
		iron: 15
	},
	{
		name: "6 inch Roasted Garlic",
		serving_size: 82,
		calories: 230,
		calories_from_fat: 25,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 1240,
		carbohydrates: 45,
		dietary_fiber: 2,
		sugars: 7,
		protein: 8,
		vitamin_a: 4,
		vitamin_c: 45,
		calcium: 35,
		iron: 15
	},
	{
		name: "6 inch Sourdough Bread",
		serving_size: 78,
		calories: 210,
		calories_from_fat: 25,
		total_fat: 3,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 210,
		carbohydrates: 41,
		dietary_fiber: 3,
		sugars: 2,
		protein: 8,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 4,
		iron: 6
	},
	{
		name: "Garlic Bread (NEW)",
		serving_size: 74,
		calories: 210,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 540,
		carbohydrates: 40,
		dietary_fiber: 2,
		sugars: 0,
		protein: 7,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 30,
		iron: 15
	},
	# {
	# 	name: "Mini Italian (White) Bread",
	# 	serving_size: 47,
	# 	calories: 130,
	# 	calories_from_fat: 15,
	# 	total_fat: 1.5,
	# 	saturated_fat: 0,
	# 	trans_fat: 0,
	# 	cholesterol: 0,
	# 	sodium: 180,
	# 	carbohydrates: 25,
	# 	dietary_fiber: 1,
	# 	sugars: 3,
	# 	protein: 5,
	# 	vitamin_a: 0,
	# 	vitamin_c: 0,
	# 	calcium: 20,
	# 	iron: 8
	# },
	# {
	# 	name: "Mini Wheat Bread",
	# 	serving_size: 52,
	# 	calories: 140,
	# 	calories_from_fat: 15,
	# 	total_fat: 1.5,
	# 	saturated_fat: 0,
	# 	trans_fat: 0,
	# 	cholesterol: 0,
	# 	sodium: 180,
	# 	carbohydrates: 27,
	# 	dietary_fiber: 3,
	# 	sugars: 3,
	# 	protein: 5,
	# 	vitamin_a: 0,
	# 	vitamin_c: 0,
	# 	calcium: 20,
	# 	iron: 8
	# }
]);

Condiments = Condiments.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Bacon (2 strips)",
		serving_size: 9,
		calories: 45,
		calories_from_fat: 30,
		total_fat: 3.5,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 190,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 3,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Cheddar Cheese (2 triangles)",
		serving_size: 15,
		calories: 60,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 95,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 4,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 0
	},
	{
		name: "Chipotle Southwest",
		serving_size: 21,
		calories: 100,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 220,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Fat Free Honey Mustard",
		serving_size: 21,
		calories: 30,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 120,
		carbohydrates: 7,
		dietary_fiber: 0,
		sugars: 6,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 2
	},
	{
		name: "Fat Free Sweet Onion",
		serving_size: 21,
		calories: 40,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 85,
		carbohydrates: 9,
		dietary_fiber: 0,
		sugars: 8,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Light Mayonnaise (1 T)",
		serving_size: 15,
		calories: 50,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 5,
		sodium: 100,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Mayonnaise (1 T)",
		serving_size: 15,
		calories: 110,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 80,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Mustard, Yellow & Deli Brown (2 tsp)",
		serving_size: 10,
		calories: 5,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 115,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Olive Oil Blend (1 tsp)",
		serving_size: 7,
		calories: 45,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Pepperjack Cheese (2 triangles)",
		serving_size: 11,
		calories: 50,
		calories_from_fat: 35,
		total_fat: 4,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 140,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 2,
		vitamin_a: 4,
		vitamin_c: 4,
		calcium: 10,
		iron: 0
	},
	{
		name: "Pepperoni",
		serving_size: 18,
		calories: 80,
		calories_from_fat: 70,
		total_fat: 7,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 410,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 1,
		protein: 4,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Processed American Cheese (2 triangles)",
		serving_size: 11,
		calories: 40,
		calories_from_fat: 30,
		total_fat: 3.5,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 200,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 2,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 6,
		iron: 0
	},
	{
		name: "Provolone Cheese (2 half circles)",
		serving_size: 14,
		calories: 50,
		calories_from_fat: 35,
		total_fat: 4,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 125,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 4,
		vitamin_a: 2,
		vitamin_c: 0,
		calcium: 10,
		iron: 0
	},
	{
		name: "Ranch (amount on 6 inch sub)",
		serving_size: 21,
		calories: 110,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 5,
		sodium: 200,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 1,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Shredded Monterey Blend",
		serving_size: 14,
		calories: 50,
		calories_from_fat: 40,
		total_fat: 4.5,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 90,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 3,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 0
	},
	{
		name: "Swiss Cheese (2 triangles)",
		serving_size: 14,
		calories: 50,
		calories_from_fat: 35,
		total_fat: 4.5,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 30,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 4,
		vitamin_a: 2,
		vitamin_c: 0,
		calcium: 15,
		iron: 0
	},
	{
		name: "Vinegar (1 tsp)",
		serving_size: 8,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
});

Vegetables = Vegetables.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Avocado",
		serving_size: 35,
		calories: 60,
		calories_from_fat: 50,
		total_fat: 5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 3,
		dietary_fiber: 2,
		sugars: 0,
		protein: 1,
		vitamin_a: 0,
		vitamin_c: 180,
		calcium: 0,
		iron: 0
	},
	{
		name: "Banana Peppers (3 rings)",
		serving_size: 4,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 20,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 6,
		calcium: 0,
		iron: 0
	},
	{
		name: "Cucumbers (3 slices)",
		serving_size: 13,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Green Peppers (3 strips)",
		serving_size: 7,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 10,
		calcium: 0,
		iron: 0
	},
	{
		name: "Jalapeno Peppers (3 rings)",
		serving_size: 4,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 70,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 2,
		calcium: 0,
		iron: 0
	},
	{
		name: "Lettuce",
		serving_size: 21,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Olives (3 rings)",
		serving_size: 3,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 25,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Onions",
		serving_size: 7,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Pickles (3 chips)",
		serving_size: 9,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 125,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Spinach",
		serving_size: 2,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Tomato (3 wheels)",
		serving_size: 34,
		calories: 5,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 1,
		protein: 0,
		vitamin_a: 6,
		vitamin_c: 8,
		calcium: 0,
		iron: 0
	},
});

Salads = Salads.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Black Forest Ham Salad",
		serving_size: 340,
		calories: 110,
		calories_from_fat: 25,
		total_fat: 3,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 600,
		carbohydrates: 12,
		dietary_fiber: 4,
		sugars: 6,
		protein: 12,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 10
	},
	{
		name: "Chicken Teriyaki with Spinach",
		serving_size: 415,
		calories: 220,
		calories_from_fat: 30,
		total_fat: 3,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 70,
		sodium: 610,
		carbohydrates: 23,
		dietary_fiber: 4,
		sugars: 14,
		protein: 27,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 8,
		iron: 10
	},
	{
		name: "Oven Roasted Chicken Salad",
		serving_size: 354,
		calories: 140,
		calories_from_fat: 25,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 50,
		sodium: 280,
		carbohydrates: 10,
		dietary_fiber: 4,
		sugars: 4,
		protein: 19,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 8,
		iron: 10
	},
	{
		name: "Roast Beef Salad",
		serving_size: 354,
		calories: 140,
		calories_from_fat: 30,
		total_fat: 3.5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 460,
		carbohydrates: 11,
		dietary_fiber: 4,
		sugars: 5,
		protein: 19,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 20
	},
	{
		name: "Subway Club® Salad",
		serving_size: 361,
		calories: 140,
		calories_from_fat: 30,
		total_fat: 3.5,
		saturated_fat: 1,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 590,
		carbohydrates: 12,
		dietary_fiber: 4,
		sugars: 5,
		protein: 18,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 15
	},
	{
		name: "Sweet Onion Chicken Teriyaki Salad",
		serving_size: 411,
		calories: 230,
		calories_from_fat: 25,
		total_fat: 3,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 50,
		sodium: 650,
		carbohydrates: 32,
		dietary_fiber: 4,
		sugars: 22,
		protein: 20,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 8,
		iron: 15
	},
	{
		name: "Turkey Breast & Ham Salad",
		serving_size: 340,
		calories: 110,
		calories_from_fat: 25,
		total_fat: 2.5,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 25,
		sodium: 530,
		carbohydrates: 12,
		dietary_fiber: 4,
		sugars: 5,
		protein: 12,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 10
	},
	{
		name: "Turkey Breast Salad",
		serving_size: 340,
		calories: 110,
		calories_from_fat: 20,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 460,
		carbohydrates: 12,
		dietary_fiber: 4,
		sugars: 5,
		protein: 12,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 10
	},
	{
		name: "Veggie Delite® Salad",
		serving_size: 284,
		calories: 60,
		calories_from_fat: 10,
		total_fat: 1,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 75,
		carbohydrates: 10,
		dietary_fiber: 4,
		sugars: 4,
		protein: 3,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 6,
		iron: 10
	},
	{
		name: "Applewood Pulled Pork Salad",
		serving_size: 370,
		calories: 230,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 45,
		sodium: 640,
		carbohydrates: 19,
		dietary_fiber: 3,
		sugars: 15,
		protein: 19,
		vitamin_a: 25,
		vitamin_c: 50,
		calcium: 4,
		iron: 6
	},
	{
		name: "BBQ Oven Roasted Chicken Melt",
		serving_size: 416,
		calories: 260,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 75,
		sodium: 910,
		carbohydrates: 25,
		dietary_fiber: 4,
		sugars: 16,
		protein: 26,
		vitamin_a: 50,
		vitamin_c: 70,
		calcium: 15,
		iron: 10
	},
	{
		name: "BBQ Steak & Bacon Melt Salad",
		serving_size: 374,
		calories: 260,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 6,
		trans_fat: 0,
		cholesterol: 55,
		sodium: 1020,
		carbohydrates: 15,
		dietary_fiber: 4,
		sugars: 6,
		protein: 24,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 15,
		iron: 15
	},
	{
		name: "Big Hot Pastrami Melt Salad",
		serving_size: 394,
		calories: 400,
		calories_from_fat: 300,
		total_fat: 29,
		saturated_fat: 11,
		trans_fat: 0,
		cholesterol: 85,
		sodium: 1250,
		carbohydrates: 12,
		dietary_fiber: 4,
		sugars: 4,
		protein: 23,
		vitamin_a: 25,
		vitamin_c: 70,
		calcium: 10,
		iron: 15
	},
	{
		name: "Big Philly Cheesesteak Salad",
		serving_size: 418,
		calories: 330,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 8,
		trans_fat: 1,
		cholesterol: 85,
		sodium: 1080,
		carbohydrates: 17,
		dietary_fiber: 5,
		sugars: 6,
		protein: 32,
		vitamin_a: 60,
		vitamin_c: 50,
		calcium: 25,
		iron: 20
	},
	{
		name: "Chicken Cordon Bleu Melt Salad",
		serving_size: 436,
		calories: 270,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 75,
		sodium: 990,
		carbohydrates: 25,
		dietary_fiber: 4,
		sugars: 17,
		protein: 26,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 15,
		iron: 15
	},
	{
		name: "Chipotle Chicken & Cheese Salad",
		serving_size: 380,
		calories: 300,
		calories_from_fat: 160,
		total_fat: 18,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 55,
		sodium: 1000,
		carbohydrates: 15,
		dietary_fiber: 4,
		sugars: 6,
		protein: 20,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 15,
		iron: 15
	},
	{
		name: "Chipotle Steak & Cheese Salad",
		serving_size: 380,
		calories: 300,
		calories_from_fat: 160,
		total_fat: 18,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 55,
		sodium: 1000,
		carbohydrates: 15,
		dietary_fiber: 4,
		sugars: 6,
		protein: 20,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 15,
		iron: 15
	},
	{
		name: "Double Chicken Salad",
		serving_size: 425,
		calories: 220,
		calories_from_fat: 35,
		total_fat: 4.5,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 100,
		sodium: 490,
		carbohydrates: 10,
		dietary_fiber: 4,
		sugars: 4,
		protein: 36,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 8,
		iron: 15
	},
	{
		name: "Fritos® Chicken Enchilada Melt Salad",
		serving_size: 448,
		calories: 510,
		calories_from_fat: 320,
		total_fat: 36,
		saturated_fat: 8,
		trans_fat: 0,
		cholesterol: 30,
		sodium: 1300,
		carbohydrates: 26,
		dietary_fiber: 6,
		sugars: 8,
		protein: 22,
		vitamin_a: 60,
		vitamin_c: 60,
		calcium: 20,
		iron: 15
	},
	{
		name: "Spicy Tuna Salad",
		serving_size: 386,
		calories: 380,
		calories_from_fat: 270,
		total_fat: 31,
		saturated_fat: 5,
		trans_fat: 0.5,
		cholesterol: 40,
		sodium: 880,
		carbohydrates: 13,
		dietary_fiber: 4,
		sugars: 7,
		protein: 15,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 6,
		iron: 15
	},
	{
		name: "Sriracha Chicken Melt Salad",
		serving_size: 393,
		calories: 260,
		calories_from_fat: 120,
		total_fat: 14,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 75,
		sodium: 910,
		carbohydrates: 13,
		dietary_fiber: 4,
		sugars: 7,
		protein: 22,
		vitamin_a: 60,
		vitamin_c: 70,
		calcium: 20,
		iron: 10
	},
	{
		name: "Sriracha Steak Melt Salad",
		serving_size: 393,
		calories: 300,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 5,
		trans_fat: 0.5,
		cholesterol: 60,
		sodium: 1250,
		carbohydrates: 17,
		dietary_fiber: 5,
		sugars: 8,
		protein: 20,
		vitamin_a: 60,
		vitamin_c: 60,
		calcium: 15,
		iron: 15
	},
	{
		name: "Steak & Bacon Melt Salad",
		serving_size: 402,
		calories: 270,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 5,
		trans_fat: 0.5,
		cholesterol: 75,
		sodium: 1110,
		carbohydrates: 16,
		dietary_fiber: 4,
		sugars: 6,
		protein: 29,
		vitamin_a: 50,
		vitamin_c: 50,
		calcium: 15,
		iron: 20
	},
	{
		name: "Subway Club® with Avocado Salad",
		serving_size: 411,
		calories: 250,
		calories_from_fat: 120,
		total_fat: 14,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 540,
		carbohydrates: 17,
		dietary_fiber: 8,
		sugars: 6,
		protein: 19,
		vitamin_a: 25,
		vitamin_c: 410,
		calcium: 6,
		iron: 15
	},
	{
		name: "Turkey & Bacon with Avocado Salad",
		serving_size: 419,
		calories: 270,
		calories_from_fat: 150,
		total_fat: 17,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 30,
		sodium: 650,
		carbohydrates: 18,
		dietary_fiber: 9,
		sugars: 5,
		protein: 17,
		vitamin_a: 50,
		vitamin_c: 420,
		calcium: 8,
		iron: 15
	},
	{
		name: "Turkey Jalapeno Melt Salad",
		serving_size: 377,
		calories: 250,
		calories_from_fat: 150,
		total_fat: 16,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 850,
		carbohydrates: 13,
		dietary_fiber: 4,
		sugars: 5,
		protein: 16,
		vitamin_a: 50,
		vitamin_c: 60,
		calcium: 15,
		iron: 10
	},
	{
		name: "Tuscan Chicken Salad",
		serving_size: 410,
		calories: 230,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 1060,
		carbohydrates: 23,
		dietary_fiber: 4,
		sugars: 13,
		protein: 22,
		vitamin_a: 60,
		vitamin_c: 70,
		calcium: 15,
		iron: 15
	},
});

Salad_Dressings = Salad_Dressings.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Fat Free Italian 2 oz",
		serving_size: 57,
		calories: 35,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 720,
		carbohydrates: 7,
		dietary_fiber: 0,
		sugars: 4,
		protein: 1,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 2,
		iron: 0
	},
	{
		name: "Ranch (2 oz)",
		serving_size: 57,
		calories: 320,
		calories_from_fat: 310,
		total_fat: 35,
		saturated_fat: 6,
		trans_fat: 0.5,
		cholesterol: 30,
		sodium: 560,
		carbohydrates: 3,
		dietary_fiber: 0,
		sugars: 2,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
});

Flatizzas = Flatizzas.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Flatizza",
		serving_size: Serving Size,
		calories: Calories,
		calories_from_fat: Calories From Fat,
		total_fat: Total Fat,
		saturated_fat: Saturated Fat,
		trans_fat: Trans Fat,
		cholesterol: Cholesterol,
		sodium: Sodium,
		carbohydrates: Carbohydrates,
		dietary_fiber: Dietary Fiber,
		sugars: Sugars,
		protein: Protein,
		vitamin_a: Vitamin A,
		vitamin_c: Vitamin C,
		calcium: Calcium,
		iron: Iron
	},
	{
		name: "Cheese Flatizza™",
		serving_size: 157,
		calories: 390,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 8,
		trans_fat: 0,
		cholesterol: 35,
		sodium: 810,
		carbohydrates: 42,
		dietary_fiber: 2,
		sugars: 3,
		protein: 21,
		vitamin_a: 10,
		vitamin_c: 2,
		calcium: 70,
		iron: 15
	},
	{
		name: "Pepperoni Flatizza™",
		serving_size: 181,
		calories: 500,
		calories_from_fat: 230,
		total_fat: 26,
		saturated_fat: 12,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 1340,
		carbohydrates: 43,
		dietary_fiber: 2,
		sugars: 4,
		protein: 26,
		vitamin_a: 10,
		vitamin_c: 4,
		calcium: 70,
		iron: 15
	},
	{
		name: "Spicy Italian Flatizza™",
		serving_size: 181,
		calories: 490,
		calories_from_fat: 220,
		total_fat: 25,
		saturated_fat: 11,
		trans_fat: 0,
		cholesterol: 60,
		sodium: 1290,
		carbohydrates: 43,
		dietary_fiber: 2,
		sugars: 4,
		protein: 25,
		vitamin_a: 10,
		vitamin_c: 4,
		calcium: 70,
		iron: 15
	},
	{
		name: "Veggie Flatizza™",
		serving_size: 191,
		calories: 410,
		calories_from_fat: 150,
		total_fat: 17,
		saturated_fat: 8,
		trans_fat: 0,
		cholesterol: 35,
		sodium: 850,
		carbohydrates: 44,
		dietary_fiber: 3,
		sugars: 4,
		protein: 21,
		vitamin_a: 10,
		vitamin_c: 25,
		calcium: 70,
		iron: 15
	},
});

Beverages = Beverages.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Coca Cola® Classic (21 oz, no ice)",
		serving_size: 621,
		calories: 260,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 15,
		carbohydrates: 71,
		dietary_fiber: 0,
		sugars: 71,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Diet Coke® (21 oz, no ice)",
		serving_size: 621,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 25,
		carbohydrates: 0,
		dietary_fiber: 0,
		sugars: 0,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "FUZE Black Tea with Lemon Sweet (21 oz, no ice)",
		serving_size: 621,
		calories: 170,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 43,
		dietary_fiber: 0,
		sugars: 43,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 25,
		calcium: 0,
		iron: 0
	},
	{
		name: "FUZE Green Tea (21 oz, no ice)",
		serving_size: 621,
		calories: 140,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 37,
		dietary_fiber: 0,
		sugars: 36,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 25,
		calcium: 0,
		iron: 0
	},
	{
		name: "FUZE Raspberry Tea (21 oz, no ice)",
		serving_size: 621,
		calories: 150,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 58,
		dietary_fiber: 0,
		sugars: 58,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 25,
		calcium: 0,
		iron: 0
	},
	{
		name: "FUZE Sweet Tea (21 oz, no ice)",
		serving_size: 621,
		calories: 170,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 44,
		dietary_fiber: 0,
		sugars: 44,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 25,
		calcium: 0,
		iron: 0
	},
	{
		name: "FUZE Unsweetened Tea (21 oz, no ice)",
		serving_size: 621,
		calories: 0,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 1,
		dietary_fiber: 0,
		sugars: 1,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 25,
		calcium: 0,
		iron: 0
	},
	{
		name: "Milk, Chocolate Flavored Reduced Fat (8 oz)",
		serving_size: 240,
		calories: 220,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 25,
		sodium: 230,
		carbohydrates: 32,
		dietary_fiber: 0,
		sugars: 29,
		protein: 10,
		vitamin_a: 10,
		vitamin_c: 4,
		calcium: 35,
		iron: 2
	},
	{
		name: "Milk, Low Fat (8 oz)",
		serving_size: 240,
		calories: 100,
		calories_from_fat: 20,
		total_fat: 2.5,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 120,
		carbohydrates: 12,
		dietary_fiber: 0,
		sugars: 12,
		protein: 8,
		vitamin_a: 10,
		vitamin_c: 4,
		calcium: 30,
		iron: 0
	},
	{
		name: "Minute Maid® Light Lemonade (21 oz, no ice)",
		serving_size: 621,
		calories: 15,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 15,
		carbohydrates: 3,
		dietary_fiber: 0,
		sugars: 3,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "Sprite® (21 oz, no ice)",
		serving_size: 621,
		calories: 260,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 60,
		carbohydrates: 68,
		dietary_fiber: 0,
		sugars: 68,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 0
	},
	{
		name: "1% Low Fat Milk - 12 oz",
		serving_size: 366,
		calories: 160,
		calories_from_fat: 35,
		total_fat: 3.5,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 180,
		carbohydrates: 19,
		dietary_fiber: 0,
		sugars: 17,
		protein: 12,
		vitamin_a: 15,
		vitamin_c: 6,
		calcium: 45,
		iron: 0
	},
	{
		name: "Minute Maid® Fruit Punch (100% Juice)",
		serving_size: 200,
		calories: 100,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 15,
		carbohydrates: 24,
		dietary_fiber: 0,
		sugars: 21,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 100,
		calcium: 10,
		iron: 2
	},
});

Desserts = Desserts.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Apple Slices - 1 package",
		serving_size: 71,
		calories: 35,
		calories_from_fat: 0,
		total_fat: 0,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 0,
		carbohydrates: 9,
		dietary_fiber: 2,
		sugars: 7,
		protein: 0,
		vitamin_a: 0,
		vitamin_c: 30,
		calcium: 4,
		iron: 0
	},
	{
		name: "Birthday Berry Cookie",
		serving_size: 45,
		calories: 200,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 4,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 130,
		carbohydrates: 32,
		dietary_fiber: 0,
		sugars: 19,
		protein: 2,
		vitamin_a: 8,
		vitamin_c: 0,
		calcium: 2,
		iron: 4
	},
	{
		name: "Chocolate Chip",
		serving_size: 45,
		calories: 220,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 130,
		carbohydrates: 30,
		dietary_fiber: 1,
		sugars: 18,
		protein: 2,
		vitamin_a: 6,
		vitamin_c: 0,
		calcium: 0,
		iron: 6
	},
	{
		name: "Chocolate Chunk",
		serving_size: 45,
		calories: 220,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 100,
		carbohydrates: 30,
		dietary_fiber: 1,
		sugars: 17,
		protein: 2,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 6
	},
	{
		name: "Double Chocolate",
		serving_size: 45,
		calories: 210,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 130,
		carbohydrates: 30,
		dietary_fiber: 1,
		sugars: 20,
		protein: 2,
		vitamin_a: 6,
		vitamin_c: 0,
		calcium: 2,
		iron: 4
	},
	{
		name: "Gingerbread",
		serving_size: 45,
		calories: 200,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 140,
		carbohydrates: 32,
		dietary_fiber: 1,
		sugars: 0,
		protein: 2,
		vitamin_a: 6,
		vitamin_c: 0,
		calcium: 0,
		iron: 6
	},
	{
		name: "M & M™",
		serving_size: 45,
		calories: 210,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 100,
		carbohydrates: 32,
		dietary_fiber: 1,
		sugars: 18,
		protein: 2,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 2,
		iron: 6
	},
	{
		name: "Oatmeal Raisin",
		serving_size: 45,
		calories: 200,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 4,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 130,
		carbohydrates: 30,
		dietary_fiber: 1,
		sugars: 16,
		protein: 3,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 2,
		iron: 6
	},
	{
		name: "Peanut Butter",
		serving_size: 45,
		calories: 220,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 130,
		carbohydrates: 26,
		dietary_fiber: 1,
		sugars: 16,
		protein: 4,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 2,
		iron: 6
	},
	{
		name: "Raspberry Cheesecake",
		serving_size: 45,
		calories: 200,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 120,
		carbohydrates: 29,
		dietary_fiber: 0,
		sugars: 16,
		protein: 2,
		vitamin_a: 6,
		vitamin_c: 0,
		calcium: 2,
		iron: 4
	},
	{
		name: "Sugar",
		serving_size: 45,
		calories: 220,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 6,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 130,
		carbohydrates: 28,
		dietary_fiber: 1,
		sugars: 14,
		protein: 2,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 0,
		iron: 4
	},
	{
		name: "White Macadamia Nut",
		serving_size: 45,
		calories: 220,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 130,
		carbohydrates: 29,
		dietary_fiber: 1,
		sugars: 18,
		protein: 2,
		vitamin_a: 6,
		vitamin_c: 0,
		calcium: 2,
		iron: 4
	},
});
Soups = Soups.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Beef Chili (8 oz)",
		serving_size: 255,
		calories: 350,
		calories_from_fat: 220,
		total_fat: 24,
		saturated_fat: 10,
		trans_fat: 0,
		cholesterol: 80,
		sodium: 730,
		carbohydrates: 17,
		dietary_fiber: 4,
		sugars: 7,
		protein: 15,
		vitamin_a: 40,
		vitamin_c: 4,
		calcium: 8,
		iron: 15
	},
	{
		name: "Chicken Noodle (8 oz)",
		serving_size: 255,
		calories: 100,
		calories_from_fat: 10,
		total_fat: 1,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 15,
		sodium: 720,
		carbohydrates: 12,
		dietary_fiber: 1,
		sugars: 1,
		protein: 10,
		vitamin_a: 35,
		vitamin_c: 4,
		calcium: 4,
		iron: 4
	},
	{
		name: "Chili Con Carne (10 oz)",
		serving_size: 255,
		calories: 350,
		calories_from_fat: 220,
		total_fat: 24,
		saturated_fat: 10,
		trans_fat: 0,
		cholesterol: 80,
		sodium: 730,
		carbohydrates: 17,
		dietary_fiber: 4,
		sugars: 7,
		protein: 15,
		vitamin_a: 40,
		vitamin_c: 4,
		calcium: 8,
		iron: 15
	},
	{
		name: "Clam Chowder (8 oz)",
		serving_size: 255,
		calories: 200,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 7,
		trans_fat: 0.5,
		cholesterol: 30,
		sodium: 850,
		carbohydrates: 20,
		dietary_fiber: 2,
		sugars: 3,
		protein: 5,
		vitamin_a: 0,
		vitamin_c: 4,
		calcium: 4,
		iron: 4
	},
	{
		name: "Creamy Chicken and Dumplings (8 oz)",
		serving_size: 255,
		calories: 150,
		calories_from_fat: 40,
		total_fat: 4.5,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 40,
		sodium: 740,
		carbohydrates: 20,
		dietary_fiber: 3,
		sugars: 3,
		protein: 8,
		vitamin_a: 20,
		vitamin_c: 10,
		calcium: 4,
		iron: 6
	},
	{
		name: "Creamy Wild and Brown Rice (8 oz)",
		serving_size: 255,
		calories: 180,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 4,
		trans_fat: 0.5,
		cholesterol: 35,
		sodium: 820,
		carbohydrates: 16,
		dietary_fiber: 2,
		sugars: 4,
		protein: 6,
		vitamin_a: 20,
		vitamin_c: 4,
		calcium: 8,
		iron: 2
	},
	{
		name: "Golden Broccoli and Cheese (8 oz)",
		serving_size: 255,
		calories: 150,
		calories_from_fat: 70,
		total_fat: 7,
		saturated_fat: 4.5,
		trans_fat: 0.5,
		cholesterol: 25,
		sodium: 710,
		carbohydrates: 15,
		dietary_fiber: 1,
		sugars: 6,
		protein: 5,
		vitamin_a: 20,
		vitamin_c: 40,
		calcium: 15,
		iron: 20
	},
	{
		name: "Green Chili and Tomato (8 oz)",
		serving_size: 255,
		calories: 90,
		calories_from_fat: 20,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 680,
		carbohydrates: 14,
		dietary_fiber: 3,
		sugars: 5,
		protein: 2,
		vitamin_a: 8,
		vitamin_c: 25,
		calcium: 4,
		iron: 6
	},
	{
		name: "Loaded Baked Potato (8 oz)",
		serving_size: 255,
		calories: 220,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 6,
		trans_fat: 0.5,
		cholesterol: 40,
		sodium: 840,
		carbohydrates: 23,
		dietary_fiber: 2,
		sugars: 4,
		protein: 7,
		vitamin_a: 0,
		vitamin_c: 10,
		calcium: 8,
		iron: 4
	},
	{
		name: "Minestrone (8 oz)",
		serving_size: 255,
		calories: 90,
		calories_from_fat: 10,
		total_fat: 1,
		saturated_fat: 0,
		trans_fat: 0,
		cholesterol: 0,
		sodium: 740,
		carbohydrates: 17,
		dietary_fiber: 5,
		sugars: 4,
		protein: 4,
		vitamin_a: 40,
		vitamin_c: 4,
		calcium: 6,
		iron: 6
	},
	{
		name: "Poblano Corn Chowder (8 oz)",
		serving_size: 255,
		calories: 150,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 4,
		trans_fat: 0.5,
		cholesterol: 20,
		sodium: 560,
		carbohydrates: 18,
		dietary_fiber: 2,
		sugars: 7,
		protein: 5,
		vitamin_a: 4,
		vitamin_c: 4,
		calcium: 10,
		iron: 4
	},
	{
		name: "Vegetable Beef (8 oz)",
		serving_size: 255,
		calories: 90,
		calories_from_fat: 15,
		total_fat: 2,
		saturated_fat: 0.5,
		trans_fat: 0,
		cholesterol: 5,
		sodium: 730,
		carbohydrates: 15,
		dietary_fiber: 3,
		sugars: 3,
		protein: 4,
		vitamin_a: 70,
		vitamin_c: 4,
		calcium: 4,
		iron: 4
	},
});

Breakfasts = Breakfasts.create([
	{
		name: "",
		serving_size: "",
		calories: "",
		calories_from_fat: "",
		total_fat: "",
		saturated_fat: "",
		trans_fat: "",
		cholesterol: "",
		sodium: "",
		carbohydrates: "",
		dietary_fiber: "",
		sugars: "",
		protein: "",
		vitamin_a: "",
		vitamin_c: "",
		calcium: "",
		iron: ""
	},
	{
		name: "Bacon, Egg (white) & Cheese with Avocado",
		serving_size: 113,
		calories: 220,
		calories_from_fat: 90,
		total_fat: 9,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 580,
		carbohydrates: 23,
		dietary_fiber: 2,
		sugars: 1,
		protein: 11,
		vitamin_a: 2,
		vitamin_c: 90,
		calcium: 20,
		iron: 8
	},
	{
		name: "Bacon, Egg (White) and Cheese",
		serving_size: 96,
		calories: 190,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 580,
		carbohydrates: 21,
		dietary_fiber: 1,
		sugars: 1,
		protein: 11,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 20,
		iron: 8
	},
	{
		name: "Black Forest Ham, Egg White & Cheese",
		serving_size: 105,
		calories: 180,
		calories_from_fat: 50,
		total_fat: 5,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 620,
		carbohydrates: 22,
		dietary_fiber: 1,
		sugars: 1,
		protein: 12,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 20,
		iron: 8
	},
	{
		name: "Egg (White) & Cheese",
		serving_size: 91,
		calories: 170,
		calories_from_fat: 45,
		total_fat: 5,
		saturated_fat: 1.5,
		trans_fat: 0,
		cholesterol: 5,
		sodium: 490,
		carbohydrates: 21,
		dietary_fiber: 1,
		sugars: 1,
		protein: 9,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 20,
		iron: 8
	},
	{
		name: "Egg White with Cheese and Avocado",
		serving_size: 109,
		calories: 200,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 5,
		sodium: 490,
		carbohydrates: 23,
		dietary_fiber: 2,
		sugars: 1,
		protein: 10,
		vitamin_a: 2,
		vitamin_c: 90,
		calcium: 20,
		iron: 8
	},
	{
		name: "Steak, Egg (White) and Cheese",
		serving_size: 108,
		calories: 190,
		calories_from_fat: 50,
		total_fat: 6,
		saturated_fat: 2,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 620,
		carbohydrates: 22,
		dietary_fiber: 1,
		sugars: 1,
		protein: 13,
		vitamin_a: 0,
		vitamin_c: 0,
		calcium: 20,
		iron: 10
	},
	{
		name: "6 inch Bacon, Egg (White) & Cheese with Avocado",
		serving_size: 218,
		calories: 430,
		calories_from_fat: 150,
		total_fat: 17,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 1100,
		carbohydrates: 48,
		dietary_fiber: 6,
		sugars: 5,
		protein: 23,
		vitamin_a: 4,
		vitamin_c: 180,
		calcium: 60,
		iron: 15
	},
	{
		name: "6 inch Bacon, Egg (White) and Cheese",
		serving_size: 183,
		calories: 370,
		calories_from_fat: 100,
		total_fat: 11,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 20,
		sodium: 1090,
		carbohydrates: 45,
		dietary_fiber: 4,
		sugars: 5,
		protein: 23,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 60,
		iron: 15
	},
	{
		name: "6 inch Egg (White) & Cheese",
		serving_size: 174,
		calories: 320,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 910,
		carbohydrates: 44,
		dietary_fiber: 4,
		sugars: 5,
		protein: 19,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 60,
		iron: 15
	},
	{
		name: "6 inch Egg White & Cheese (with ham)",
		serving_size: 202,
		calories: 350,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 25,
		sodium: 1170,
		carbohydrates: 45,
		dietary_fiber: 4,
		sugars: 6,
		protein: 24,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 60,
		iron: 15
	},
	{
		name: "6 inch Egg White with Cheese and Avocado",
		serving_size: 209,
		calories: 380,
		calories_from_fat: 120,
		total_fat: 13,
		saturated_fat: 4,
		trans_fat: 0,
		cholesterol: 10,
		sodium: 910,
		carbohydrates: 47,
		dietary_fiber: 6,
		sugars: 5,
		protein: 20,
		vitamin_a: 4,
		vitamin_c: 180,
		calcium: 60,
		iron: 15
	},
	{
		name: "6 inch Steak, Egg (White) & Cheese",
		serving_size: 216,
		calories: 390,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 4,
		trans_fat: 0,
		cholesterol: 35,
		sodium: 1240,
		carbohydrates: 47,
		dietary_fiber: 4,
		sugars: 6,
		protein: 28,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 60,
		iron: 20
	},
	{
		name: "6 inch Bacon, Egg & Cheese",
		serving_size: 183,
		calories: 410,
		calories_from_fat: 140,
		total_fat: 16,
		saturated_fat: 6,
		trans_fat: 0,
		cholesterol: 235,
		sodium: 1050,
		carbohydrates: 45,
		dietary_fiber: 5,
		sugars: 6,
		protein: 23,
		vitamin_a: 8,
		vitamin_c: 0,
		calcium: 40,
		iron: 20
	},
	{
		name: "6 inch Bacon, Egg & Cheese with Avocado",
		serving_size: 218,
		calories: 470,
		calories_from_fat: 190,
		total_fat: 21,
		saturated_fat: 7,
		trans_fat: 0,
		cholesterol: 235,
		sodium: 1050,
		carbohydrates: 48,
		dietary_fiber: 7,
		sugars: 7,
		protein: 23,
		vitamin_a: 8,
		vitamin_c: 180,
		calcium: 45,
		iron: 20
	},
	{
		name: "6 inch Black Forest Ham, Egg & Cheese",
		serving_size: 202,
		calories: 390,
		calories_from_fat: 120,
		total_fat: 13,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 240,
		sodium: 1120,
		carbohydrates: 45,
		dietary_fiber: 5,
		sugars: 7,
		protein: 24,
		vitamin_a: 8,
		vitamin_c: 0,
		calcium: 40,
		iron: 20
	},
	{
		name: "6 inch Egg & Cheese",
		serving_size: 174,
		calories: 360,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 4.5,
		trans_fat: 0,
		cholesterol: 230,
		sodium: 860,
		carbohydrates: 44,
		dietary_fiber: 5,
		sugars: 6,
		protein: 19,
		vitamin_a: 8,
		vitamin_c: 0,
		calcium: 40,
		iron: 20
	},
	{
		name: "6 inch Steak, Egg & Cheese",
		serving_size: 216,
		calories: 430,
		calories_from_fat: 130,
		total_fat: 15,
		saturated_fat: 5,
		trans_fat: 0,
		cholesterol: 255,
		sodium: 1190,
		carbohydrates: 47,
		dietary_fiber: 5,
		sugars: 7,
		protein: 28,
		vitamin_a: 8,
		vitamin_c: 0,
		calcium: 40,
		iron: 20
	},
	{
		name: "Bacon, Egg & Cheese with Avocado",
		serving_size: 113,
		calories: 240,
		calories_from_fat: 110,
		total_fat: 12,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 115,
		sodium: 560,
		carbohydrates: 23,
		dietary_fiber: 2,
		sugars: 2,
		protein: 11,
		vitamin_a: 4,
		vitamin_c: 90,
		calcium: 10,
		iron: 10
	},
	{
		name: "Bacon, Egg and Cheese",
		serving_size: 96,
		calories: 210,
		calories_from_fat: 80,
		total_fat: 9,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 115,
		sodium: 560,
		carbohydrates: 21,
		dietary_fiber: 1,
		sugars: 2,
		protein: 11,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 10
	},
	{
		name: "Black Forest Ham, Egg & Cheese",
		serving_size: 105,
		calories: 200,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 120,
		sodium: 590,
		carbohydrates: 22,
		dietary_fiber: 1,
		sugars: 2,
		protein: 12,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 10
	},
	{
		name: "Egg & Cheese",
		serving_size: 91,
		calories: 190,
		calories_from_fat: 60,
		total_fat: 7,
		saturated_fat: 2.5,
		trans_fat: 0,
		cholesterol: 110,
		sodium: 460,
		carbohydrates: 21,
		dietary_fiber: 1,
		sugars: 2,
		protein: 9,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 10
	},
	{
		name: "Steak, Egg and Cheese",
		serving_size: 108,
		calories: 210,
		calories_from_fat: 70,
		total_fat: 8,
		saturated_fat: 3,
		trans_fat: 0,
		cholesterol: 125,
		sodium: 590,
		carbohydrates: 22,
		dietary_fiber: 1,
		sugars: 2,
		protein: 13,
		vitamin_a: 4,
		vitamin_c: 0,
		calcium: 10,
		iron: 10
	},
	{
		name: "Sunrise Subway Melt®",
		serving_size: 147,
		calories: 240,
		calories_from_fat: 90,
		total_fat: 10,
		saturated_fat: 3.5,
		trans_fat: 0,
		cholesterol: 130,
		sodium: 780,
		carbohydrates: 23,
		dietary_fiber: 2,
		sugars: 3,
		protein: 16,
		vitamin_a: 8,
		vitamin_c: 4,
		calcium: 10,
		iron: 10
	},
])


















# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CoffeeShop.destroy_all
Bean.destroy_all
Event.destroy_all

# The year/month/day do not matter, since we are getting the seconds since midnight
# Time.new(year,month,day, hour,minute,second, offset_from_GMT)
coffee_shops = CoffeeShop.create([
	{
		name: "General Assembly",
		address: "1520 2nd St; Santa Monica, CA",
		phone: "",
		website: "http://generalassemb.ly",
		time_open: Time.new(2012,10,10, 8,0,0, "+07:00").seconds_since_midnight,
		time_closed: Time.new(2012,10,10, 22,0,0, "+07:00").seconds_since_midnight
	},
	{
		name: "Starbucks",
		address: "3rd Street Promenade",
		phone: "",
		website: "http://starbucks.com",
		time_open: Time.new(2012,10,10, 6,0,0, "+07:00").seconds_since_midnight,
		time_closed: Time.new(2012,10,10, 8,0,0, "+07:00").seconds_since_midnight	
	}
]);

beans = Bean.create([
	{
		name: "GA Coffee",
		roast: "medium",
		origin: "Kenya",
		quantity: "3.75",

		coffee_shop: coffee_shops[0]   # GA
	},
	{
		name: "Light Roast",
		roast: "light",
		origin: "Blend",
		quantity: "43.0",

		coffee_shop: coffee_shops[1]   # Starbucks
	},
	{
		name: "Pike's Place",
		roast: "medium",
		origin: "Blend",
		quantity: "13.75",

		coffee_shop: coffee_shops[1]   # Starbucks
	}
]);


events = Event.create([
	{
		title: "Happy Hour",
		date_time: DateTime.new(2014, 9, 8, 23, 00, 00),
		description: "Half-price on all house roasts",

		coffee_shop: coffee_shops[0]   # GA
	},
	{
		title: "Open Mic",
		date_time: DateTime.new(2014, 9, 8, 17, 00, 00),
		description: "You have five minutes to be funny or sing a song.",

		coffee_shop: coffee_shops[1]   # Starbucks
	},
]);